### ISSUE TITLE
Bug in Tour Operator plugin which causes Trust Pilot Slider to break.

### ISSUE THREAD

**Issue by jlaguma** [lightspeeddevelopment/tour-operator#108]
There is a bug is in "Tour Operator" plugin. The bug causes multiple initializations of slick slider.
When the slider is active,  and you view the site in "mobile" it gives a JS error in the console.
That error doesn't stop the carousel from working, but it stops the 3rd party analytics scripts from submitting and doing their thing.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open https://southerndestinations.com/
That is all that is needed. If slick slider is enabled (wp-content\themes\sd-lsx-child\assets\js\custom.js - line 408), then 3rd party analytics can no longer submit.

**Expected behavior**
Trust Pilot slider as well as 3rd party analytics should all work correctly.

**Mobile**
 - Device: any mobile device with width below 767 pixels.

**Additional context**
Bug location and fix description:
In file:
\wp-content\plugins\tour-operator\assets\js\src\custom.js

On line 294:
$( '.gallery' ).slick( {

To fix it, it should be like so:
$( '.gallery' ).not('.slick-initialized').slick( {

**Comment by jlaguma** [comment]
Issue addressed: https://github.com/lightspeeddevelopment/tour-operator/commit/75d641def2e9f1f3d2b55cc037b69c8424f95865

**Comment by krugazul** [comment]
@jlaguma I have tested the fix,  I no longer see the JS error in the console.  So its working great thanks.

I [uncommented](https://github.com/lightspeeddevelopment/sd-lsx-child/commit/65bf01da138b8aedbe2c161f8284427c522631d2) a call in the shortcode to the `show_score` shortcode, which adds a 4th panel.

![Screenshot 2020-01-24 at 09 56 19](https://user-images.githubusercontent.com/1805603/73053295-0a76ec00-3e90-11ea-97bb-9c67537ecc08.png)
