### ISSUE TITLE
Lazy Loading for the galleries is broken

### ISSUE THREAD

**Issue by krugazul** [lightspeeddevelopment/tour-operator#11]
Hi Fernando,  i change the name of one of the filters that adds the lazy loading to envira, need some help finding it and correcting.

https://to-demo.lsdev.biz/tour/best-of-botswana/

**Comment by nandotess** [comment]
@krugazul it's done, the issue was related with <noscript> tag (was not allowed to display). Only happened when the lazy load was disabled.
