### ISSUE TITLE
Layout with 2 columns = sidebar floats a bit upwards

### ISSUE THREAD

**Issue by nandotess** [lightspeeddevelopment/tour-operator#12]
@krugazul:

> If you set the layout to 2 columns, then the sidebar floats a bit upwards. which sits over the navgation and the breadcrumb.

Initial reported in task #9.

**Comment by nandotess** [comment]
@krugazul I need more details how can I replicate. Thanks.

**Comment by krugazul** [comment]
Hey Bud,  this has been fixed.  We took care of it on one of the Internal Asana tasks.
