### ISSUE TITLE
Plugin Activation Issues

### ISSUE THREAD

**Issue by sakinshrestha** [lightspeeddevelopment/tour-operator#15]
* Got following script errors on theme welcome page:
```
TypeError: a is undefined   
TypeError: i is not a function
TypeError: jQuery is not a function
```
Check console
* Getting following error on front end
`TypeError: jQuery(...).scrollspy ics not a function .../assets/js/custom.min.js?ver=1.0.5 line 1`

**Comment by nandotess** [comment]
Closed automatically via commit. Issue related with Mailchimp external script. Fixed the import way.
