### ISSUE TITLE
Output escaping issues, Always use esc_url when sanitizing URLs

### ISSUE THREAD

**Issue by sakinshrestha** [lightspeeddevelopment/tour-operator#16]
* Escape using `esc_url()` in the following files*
    * classes/class-frontend.php, line no 340 `get_permalink()`
    * includes/layout.php, line no 59 `get_permalink()`
    * includes/template-tags/accommodation.php, line no 113 and 118 `get_term_link( $heading->slug, 'facility' )`
    * includes/template-tags/general.php, line no 172 `$link_slug`
    * includes/template-tags/helpers.php, line no 555 `get_the_permalink($cp->ID)`
    * includes/widgets/post-type-widget.php, line no 176 `$title_link`
    * includes/widgets/post-type-widget.php, line no 596 `$link`
        * Also, in few lines above this, why have you used `wp_kses_post`?
    * includes/widgets/taxonomy-widget.php, line no 172 `$title_link`
    * includes/widgets/taxonomy-widget.php, line no 540 `$link`
        * Also, in few lines above this, why have you used `wp_kses_post`?

* Escape using `esc_url()` in the following files for all image sources*
    * classes/class-admin.php, line no 531 `$image_preview[0]`
    * classes/class-itinerary.php, line no 303 `$thumbnail_src`
    * classes/class-units.php, line no 203 `$thumbnail_src`
    * includes/template-tags/helpers.php, line no 167 `$img[0]`
    * templates/content-gallery.php, line no 13 `$srcset[0]`
    * vendor/Custom-Meta-Boxes/classes.fields.php line 452 $src
 
* Use `esc_url()` instead of `esc_attr` in the following files*
     * templates/content-widget-accommodation-brand.php, line no 24
     * templates/content-widget-accommodation-type.php, line no 22
     * templates/content-widget-travel-style.php, line no 22

**Comment by viscosho** [comment]
@krugazul I have fixed these issues, check the following pull request: https://github.com/lightspeeddevelopment/tour-operator/pull/110
