### ISSUE TITLE
Other output escaping issues

### ISSUE THREAD

**Issue by sakinshrestha** [lightspeeddevelopment/tour-operator#17]
* Use `antispambot()` function before showing email on front end
     * In includes/template-tags/general.php, line no 453, you need to use antispambot function, E.g:
     `<div class="meta email"><i class="fa fa-envelope orange"></i> <a href="mailto:<?php echo esc_attr( antispambot( $fields[ 'enquiry_contact_email' ] ) ); ?>"><?php echo esc_html( antispambot( $fields[ 'enquiry_contact_email' ] ) ); ?></a></div>`
* Escape using `esc_attr()` in the following
    * classes/class-frontend.php, line no 340 `get_the_ID()`
    * templates/content-gallery.php, line no 13 `apply_filters('the_title',$image->post_title)`

**Comment by viscosho** [comment]
@krugazul  this has been fixed in this pull request that deals with sanitization: https://github.com/lightspeeddevelopment/tour-operator/pull/110
