### ISSUE TITLE
Unnecessary escaping

### ISSUE THREAD

**Issue by sakinshrestha** [lightspeeddevelopment/tour-operator#18]
* In following, you have used `esc_url()` when initializing the link and `wp_kses_post` on escaping. Remove both because static content does not need escaping
    * in includes/settings/add-ons.php
        * ln 28 $tour_operator_link
        * ln 54 $map_link
        * ln 69 $specials_link
        * ln 84 $reviews_link
        * ln 101 $activities_link
        * ln 116 $search_link
        * ln 131 $galleries_link
        * ln 148 $vehicles_link
        * ln 163 $team_link
        * ln 178 $video_link
        * ln 195 $wetu_importer_link
    * In includes/settings/help.php
        * ln 45 $lsx_to_documentation
        * ln 63 $map_link_doc
        * ln 64 $galleries_link_doc
        * ln 65 $team_link_doc
        * ln 66 $activities_link_doc
        * ln 67 $reviews_link_doc
        * ln 68 $specials_link_doc
        * ln 69 $search_link_doc
        * ln 70 $vehicles_link_doc
        * ln 71 $videos_link_doc
        * ln 72 $wetu_importer_link_doc
        * ln 91 $tour_operator_link
        * Lines 117-130 has similar issue
    * In includes/settings/welcome.php lines 31-76
* In includes/settings/add-ons.php, line no 29-188, there is no need to escape static image sources

**Comment by viscosho** [comment]
@krugazul  this one should be closed, this is quite old, and now if we don't sanitize this content we get a warning from PHPCS and the code does not pass the WordPress standards: `All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$specials_link'.phpcs`
