### ISSUE TITLE
Unnecessary use of wp_kses_post

### ISSUE THREAD

**Issue by sakinshrestha** [lightspeeddevelopment/tour-operator#21]
* I found that `wp_kses_post` being used excessively in this plugin, so you need to check in details. Like in templates/content-gallery.php line 13. This functions here serves no purpose. 
It is being used throughout, check out issue #18

**Comment by justintadlock** [comment]
I was just catching up on the issues posted so far.  From what I'm seeing, it's more of a "doing the right thing but not quite right" kind of thing.  It's great that you're escaping, but let's escape right.

Just looking at the `content-gallery.php` template mentioned above:

```
<?php echo wp_kses_post( apply_filters( 'lsx_to_lazyload_filter_images', '<img title="'. apply_filters('the_title',$image->post_title) .'" src="'. $srcset[0] .'" />' ) ); ?>
```

I'd probably code that as something similar to this:

```
<?php printf(
	apply_filters( 'lsx_to_lazyload_filter_images', '<img title="%1$s" src="%2$s" />' ),
	esc_attr( $image->post_title ),
	esc_url( $srcset[0] )
); ?>
```

**Comment by justintadlock** [comment]
I'm definitely getting the feeling that you wanted to correct the WP code sniffer "warnings" about escaping with all the uses of `wp_kses_post()`.  If I'm correct about this, remember that it's merely a tool.  It's not 100% accurate.

Anyway, I keep coming across this in the plugin, and it's been kind of bothering me.  Here's an example from `includes/template-tags/helpers.php`:

```
/**
 * Outputs the current terms thumbnail
 *
 * @param	$term_id string
 */
if(!function_exists('lsx_to_term_thumbnail')){
	function lsx_to_term_thumbnail($term_id = false,$size='lsx-thumbnail-wide') {
		if(false !== $term_id){
			echo wp_kses_post(lsx_to_get_term_thumbnail($term_id,$size));
		}
	}
}
/**
 * Outputs the current terms thumbnail
 *
 * @param	$term_id string
 */
if(!function_exists('lsx_to_get_term_thumbnail')){
	function lsx_to_get_term_thumbnail($term_id = false,$size='lsx-thumbnail-wide') {
		if(false !== $term_id){
			$term_thumbnail_id = get_term_meta($term_id, 'thumbnail', true);
			$img = wp_get_attachment_image_src($term_thumbnail_id,$size);
			return apply_filters( 'lsx_to_lazyload_filter_images', '<img alt="thumbnail" class="attachment-responsive wp-post-image lsx-responsive" src="'.$img[0].'" />' );
		}
	}
}
```

I'm going to rewrite that whole bit of code with escaping in the proper place.  I also took the liberty to clean up some other areas with it:

```
if ( ! function_exists( 'lsx_to_term_thumbnail' ) ) {

	function lsx_to_term_thumbnail( $term_id = false, $size = 'lsx-thumbnail-wide' ) {

		echo lsx_to_get_term_thumbnail( $term_id, $size );
	}
}

if ( ! function_exists( 'lsx_to_get_term_thumbnail' ) ) {

	function lsx_to_get_term_thumbnail( $term_id = false, $size = 'lsx-thumbnail-wide' ) {

		if ( $term_id ) {
			$thumb_id = get_term_meta( $term_id, 'thumbnail', true );

			if ( $thumb_id ) {
				$img = wp_get_attachment_image_src( $term_thumbnail_id, $size );

				if ( $img && isset( $img[0] ) ) {

					return apply_filters( 
						'lsx_to_lazyload_filter_images', 
						sprintf( 
							'<img alt="thumbnail" class="attachment-responsive wp-post-image lsx-responsive" src="%s" />',
							esc_url( $img[0] )
						)
					);
				}
			}
		}

		return '';
	}
}
```

A code sniffer is going to throw a warning on this line:

```
echo lsx_to_get_term_thumbnail( $term_id, $size );
```

But, that's OK.  We know it's good to go.  Also, you can whitelist errors that you know are safe: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki/Whitelisting-code-which-flags-errors
