### ISSUE TITLE
Prefixes classes, functions and options

### ISSUE THREAD

**Issue by sakinshrestha** [lightspeeddevelopment/tour-operator#22]
* Plugin uses `LSX_` or `lsx_` as prefix for classes and functions
* You need to use your plugin slug which is `tour_operator`
* Reason for this, is to avoid function clash with other themes and plugins
* Check http://themereview.co/prefix-all-the-things/ which is for themes, but can apply for plugins as well

**Comment by Desertsnowman** [comment]
Personally I feel that function should be prefixed, but classes should be namespaced. After all that's what namespacing is designed for.

Also, class names should be short and descriptive of their purpose like `placeholders` or `banner_integration` adding the prefix makes them longer and repetitive.

**Comment by krugazul** [comment]
Closing this,  classes have since been namespaced and prefixes have been added where neccesary
