### ISSUE TITLE
Enqueuing admin scripts/styles

### ISSUE THREAD

**Issue by sakinshrestha** [lightspeeddevelopment/tour-operator#26]
* In classes/class-admin.php method `enqueue_admin_stylescripts`, admin scripts/styles are being loaded in all admin screens
* To restrict these to certain pages only, use `$hook` parameter available. Check https://codex.wordpress.org/Plugin_API/Action_Reference/admin_enqueue_scripts#Example:_Load_CSS_File_from_a_plugin_on_specific_Admin_Page
* This issue is present everywhere where `admin_enqueue_scripts` is used. You need to check thoroughly on all files

**Comment by nandotess** [comment]
Closed automatically via commit. Hook updated.
