### ISSUE TITLE
is_ssl() check

### ISSUE THREAD

**Issue by sakinshrestha** [lightspeeddevelopment/tour-operator#29]
* In includes/settings/welcome.php, line no 8 and 9, you do not need to do ssl check. Just do it as follows:
`wp_enqueue_script( 'mailchimpembed', '//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js', array(), false, true);`

**Comment by nandotess** [comment]
Fixed on **TO 1.1**: https://github.com/lightspeeddevelopment/tour-operator/tree/v1.1.0
