### ISSUE TITLE
CTA Widget

### ISSUE THREAD

**Issue by sakinshrestha** [lightspeeddevelopment/tour-operator#30]
* See issue #31 
* Ref: includes/widgets/cta-widget.php 
* This file as mentioned in escaping issues #21 has a lot of unnecessary `wp_kses_post` calls
* Because of method `upload_scripts`, the scripts are loaded in all admin pages, you need to restrict it to only widget page as in method described in Enqueuing admin scripts/styles, issue #26
* The function here just enqueues media-upload and thickbox, which isn't being utilized
* You need a supporting JS script for this which is missing and making this method and enqueue obsolete

**Comment by nandotess** [comment]
CTA Wdiget removed on **TO 1.1**: https://github.com/lightspeeddevelopment/tour-operator/tree/v1.1.0

**Comment by nandotess** [comment]
CTA Widget removed on **TO 1.1**: https://github.com/lightspeeddevelopment/tour-operator/tree/v1.1.0
