### ISSUE TITLE
CTA Widget Usage

### ISSUE THREAD

**Issue by sakinshrestha** [lightspeeddevelopment/tour-operator#31]
* Content has `#333333` as default value
* Upload image uses old media library upload. Update it. Check: http://wordpress.stackexchange.com/questions/127299/create-image-uploader-for-widget and http://jeroensormani.com/how-to-include-the-wordpress-media-selector-in-your-plugin/
* Size and Repeat Options are dropdowns with no options
* Shows following errors on front end
```
Notice: Undefined variable: before_widget in .../includes/widgets/cta-widget.php on line 58
#333333
Notice: Undefined variable: after_widget in .../includes/widgets/cta-widget.php on line 82
```

**Comment by nandotess** [comment]
CTA Wdiget removed on **TO 1.1**: https://github.com/lightspeeddevelopment/tour-operator/tree/v1.1.0
