### ISSUE TITLE
Unnecessary wp_reset_query()

### ISSUE THREAD

**Issue by sakinshrestha** [lightspeeddevelopment/tour-operator#32]
* In following files, only `wp_reset_postdata` is sufficient, no need of `wp_reset_query`
    * includes/template-tags/destination.php
    * includes/template-tags/helpers.php
    * includes/widgets/post-type-widget.php

**Comment by nandotess** [comment]
Closed automatically via commit. Functions call `wp_reset_query()` removed. Searched by same issue in others files, no match.
