### ISSUE TITLE
Update Media Uploader

### ISSUE THREAD

**Issue by sakinshrestha** [lightspeeddevelopment/tour-operator#33]
* Theme uses thickbox ad media uploader in Widgets and custom taxonomy add/edit Pages
* Check: http://wordpress.stackexchange.com/questions/127299/create-image-uploader-for-widget and http://jeroensormani.com/how-to-include-the-wordpress-media-selector-in-your-plugin/ to update the media addition button

**Comment by justintadlock** [comment]
I just want to second this recommendation.  Adding an image for one of the taxonomy terms was almost painful.

Is anyone on your team familiar with using Backbone + Underscore templates?  If so, here's how I handle the Backbone code for a media modal: https://github.com/justintadlock/butterbean/blob/1.0/js/butterbean.js#L816-L873

And, here's the Underscore template: https://github.com/justintadlock/butterbean/blob/1.0/tmpl/control-image.php

If you're not familiar with Backbone and Underscore, it's probably not worth learning just for this small part of this project.  I just thought I'd share another method of using the media modal without having to do DOM manipulation like in the other two examples linked above.
