### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by sakinshrestha** [lightspeeddevelopment/tour-operator#34]
* Ref: https://www.lsdev.biz/documentation/homepage-configuration/
* I tried adding accommodation page, but it did not work as described in documentation above
* Only works for custom permalink structure. Not working for all permalink structures

**Comment by ashleyshaw** [comment]
@nandotess please investigate and if you think this will take a lot of time, then move to 1.1 milestone and reassign to @krugazul

**Comment by krugazul** [comment]
@ashleyshaw  and @jacquesvdhorst  this issue is no longer relevant.
