### ISSUE TITLE
Single and archive pages

### ISSUE THREAD

**Issue by sakinshrestha** [lightspeeddevelopment/tour-operator#35]
* The featured and archive pages of all Custom Post Type posts need work
* Check screenshot for new destination 
![attachment 1](https://cloud.githubusercontent.com/assets/9452203/23577572/12d91778-00eb-11e7-872c-099f780fe293.png)
* This is the case for all the CPTs registered by theme

**Comment by krugazul** [comment]
@ashleyshaw  and @jacquesvdhorst this issue is no longer relevant.
