### ISSUE TITLE
UI: Settings page tabs

### ISSUE THREAD

**Issue by justintadlock** [lightspeeddevelopment/tour-operator#40]
As in [issue #39](https://github.com/lightspeeddevelopment/tour-operator/issues/39), you should follow core's lead with your settings tabs.  The following is a screenshot of how it's done in your theme.

![settings-tabs](https://cloud.githubusercontent.com/assets/1816309/23591502/df7d6998-01b6-11e7-9018-4ebbab39c6bf.png)

This screenshot is how it's done in core on the Plugins and Themes screens:

![plugins-tabs](https://cloud.githubusercontent.com/assets/1816309/23591503/dfbbd43a-01b6-11e7-8bde-a53ce5a7b02e.png)

**Comment by ashleyshaw** [comment]
@justintadlock we totally agree and will move over to core wordpress styling, to be honest I have never thought to use those tabs, great suggestion.

**Comment by fmdalpiaz** [comment]
Hey @Desertsnowman the tabs are looking great.
I don't know if it's the right place to mention you that, but there are some inner tabs that are empty:

- **Display** > General
- **API** > Settings
- **API** > Licence Keys (it mentions licence boxes, but there is none in the page)

**Comment by Desertsnowman** [comment]
@fmdalpiaz I did notice that they are empty, and they were empty before I started. But this issue didn't mention that so left it, and assumed there was another issue about it.

**Comment by krugazul** [comment]
Hey Guys,  ive reviewed the code,   and also fixed the empty "general tab".  and the "Settings" and "License" keys tabs.    Merged back into 1.0.7.
