### ISSUE TITLE
Taxonomy naming

### ISSUE THREAD

**Issue by justintadlock** [lightspeeddevelopment/tour-operator#42]
It's standard practice to use an underscore rather than a hyphen when a taxonomy name (and post type names, for that matter) has multiple words.  So, instead of `travel-style` and `accommodation-type`, they should be named `travel_style` and `accommodation_type`, respectively.

Of course, if it's too late in the game to change these (already in use on sites), just leave them be.  But, definitely keep this in mind in the future.

**Comment by ashleyshaw** [comment]
@justintadlock I spoke to @krugazul about the taxonomy slugs, we both agree that it would have been better to use underscores, we are keen to rectify this before we get too many downloads / installs. WooCommerce update the DB from time to time when they run an upgrade, so maybe we could take a similar approach? 

@eleshar do you have any input on assisting with an SQL script maybe? Warwick could run a DB upgrade script on the next upgrade for example.

**Comment by justintadlock** [comment]
If you want to change it on existing sites, here's an example where I've done this: https://github.com/justintadlock/custom-content-portfolio/blob/2.0/portfolio.php#L247
