### ISSUE TITLE
$plugin_slug property

### ISSUE THREAD

**Issue by justintadlock** [lightspeeddevelopment/tour-operator#43]
In `classes/class-tour.php` and `classes/class-accommodation.php`, you have defined the `$plugin_slug` property.  This is very confusing because it's not the "plugin" slug.  It's the "post type" slug.

```
protected $plugin_slug = 'tour';
```

I'm just looking through the classes and wondering why the code keeps referencing the plugin slug.  That's likely to create some headaches down the line when you're looking through the code in a few years wondering the same thing.

**Comment by krugazul** [comment]
Ive gone through the post type classes,  this has been changed throughout.  we changed plugin slug to just $slug.   that way we know its for the current post types slug. (which is the "key" we use for all arrays / objects.)
