### ISSUE TITLE
Sanitizing widget options

### ISSUE THREAD

**Issue by justintadlock** [lightspeeddevelopment/tour-operator#45]
All of the widgets in `includes/widgets` need a full re-coding of the widgets' `update()` methods.  Essentially, each widget option is wrapped with `strip_tags()`.  There are a few that aren't sanitized at all.

`strip_tags()` is not really acceptable here for most options.  It's not just about sanitizing (making safe), it's also about making sure that the data is really the type of data that should be stored.

For example, the "Columns" option for the "TO Post Types" widget has only 6 allowed options.  So, in the `update()` method, this bit of code:

```
$instance['columns'] = strip_tags( $new_instance['columns'] );
```

Would work better as:

```
$instance['columns'] = in_array( $new_instance['columns'], range( 1, 6 ) ) ? $new_instance['columns'] : 1;
```

That's an example of whitelist validating, which is one of the safest and best ways to validate if you have a **known** list of values that are allowed.

Another example from the same widget is the "Title Link" field.  This is how it's currently sanitized:

```
$instance['title_link'] = strip_tags( $new_instance['title_link'] );
```

Because it's a URL, it should be sanitized like so:

```
$instance['title_link'] = esc_url_raw( $new_instance['title_link'] );
```

Always use the most appropriate method for the type of data that you expect.  Don't just run `strip_tags()` over everything.

**Comment by viscosho** [comment]
@krugazul  I have created a pull request for this issue: https://github.com/lightspeeddevelopment/tour-operator/pull/110 
Please review and test.
