### ISSUE TITLE
sanitize_text_field() and PHP superglobals

### ISSUE THREAD

**Issue by justintadlock** [lightspeeddevelopment/tour-operator#46]
I'm seeing a lot of things like this in the plugin:

```
sanitize_text_field(wp_unslash($_GET['taxonomy']))
```

I'm guessing you've been running a code sniffer that's telling you to unslash and sanitize these superglobals.  That's definitely a good idea.  However, `sanitize_text_field()` isn't generally the most appropriate function.

Like I wrote about in [issue #45](https://github.com/lightspeeddevelopment/tour-operator/issues/45), you want to always use the most appropriate function for the job.

How to deal with these will happen on a case-by-case basis.  In the example above, you could simply do this:

```
sanitize_key( $_GET['taxonomy'] )
```

No need to unslash there because `sanitize_key()` removes slashes.  A taxonomy name will only consist of characters allowed by `sanitize_key()`, so that's a good choice.

A good rule of thumb:  _just because something's technically "safe" doesn't mean that it's correct._  So, if possible, always try to make sure you're dealing with the correct type of data.

**Comment by krugazul** [comment]
Ive checked and the double sanitization has been removed.
