### ISSUE TITLE
Prefixing: Global variables

### ISSUE THREAD

**Issue by justintadlock** [lightspeeddevelopment/tour-operator#47]
In `templates/content-gallery.php`, I'm seeing reference to these two globals:

```
global $image,$size;
```

However, I can't find where those are coming from.  If these are globals that are set by your plugin, they need to be prefixed.  Those are very generic variable names and will likely conflict with something.

**Comment by ashleyshaw** [comment]
@nandotess can you please reply to @justintadlock question.

**Comment by krugazul** [comment]
This template has been removed
