### ISSUE TITLE
Broken image in taxonomy widget

### ISSUE THREAD

**Issue by justintadlock** [lightspeeddevelopment/tour-operator#49]
When using the TO Taxonomies widget, you need to check that there's an image before attempting to display it.  When a term doesn't have an image, it outputs the following HTML:

```
<img alt="thumbnail" class="attachment-responsive wp-post-image lsx-responsive" src="">
```

**Comment by nandotess** [comment]
@krugazul I remember we discussed this sometimes. It's related with the required placeholder. I guess you can resolve better than me because you have all the background related with this behaviour.

**Comment by krugazul** [comment]
@ashleyshaw and @jacquesvdhorst, this issue has been fixed.  We have a function which checks to see if the image is false or and empty string, before it outputs the image tags.

- [Function in helpers.php](https://github.com/lightspeeddevelopment/tour-operator/blob/master/includes/template-tags/helpers.php#L186)
 - [Example of it being used](https://github.com/lightspeeddevelopment/tour-operator/blob/master/templates/content-widget-travel-style.php#L20)
