### ISSUE TITLE
Create a wrapper for Tour_Operator

### ISSUE THREAD

**Issue by justintadlock** [lightspeeddevelopment/tour-operator#52]
Right now, the plugin uses a global `$tour_operator` variable.  I'm a huge fan of getting rid of globals where possible.  Because the `Tour_Operator` class is just a singleton, I'd create a wrapper in `module.php`.

Instead of this code:

```
$tour_operator = Tour_Operator::get_instance();
```

Do this:

```
function tour_operator() {
	return Tour_Operator::get_instance();
}

// Launch.
tour_operator();
```

That way, you have an easy reference to the single instance via a function rather than a global.  For example, you can take the `lsx_to_get_taxonomies()` function in the same file and do this:

```
function lsx_to_get_taxonomies() {

	return tour_operator()->get_taxonomies();
}
```

You can do the same with any other references to the global `$tour_operator` variable.  Having a dedicated wrapper function will tidy things up a bit.

**Comment by justintadlock** [comment]
Just wanted to note that you could do this for other singleton or factory classes too where you're using globals.

**Comment by krugazul** [comment]
Ive checked the code, its working with the wrapper.
