### ISSUE TITLE
Architecture: Class files should not have functions

### ISSUE THREAD

**Issue by justintadlock** [lightspeeddevelopment/tour-operator#54]
When creating `class-x.php` files, the file itself should only have the class and nothing more.  Move any extra functions to a separate file.

This is just good programming practice and will help you in the long run when managing such a large plugin.

**Comment by krugazul** [comment]
Ive run through all the class file in Branch 1.1.0 (the branch we are currently developing on).   And all extra-class functions have been moved to the "template-tag" folder.
