### ISSUE TITLE
Architecture: Overhaul organization of plugin

### ISSUE THREAD

**Issue by justintadlock** [lightspeeddevelopment/tour-operator#55]
I touched on this in [issue #44](https://github.com/lightspeeddevelopment/tour-operator/issues/44), but this is the bigger ticket that addresses the entire plugin.

As a fellow developer, I'd say one of the biggest flaws in this plugin is how things are organized.  Most of the code itself is pretty solid for a plugin of this size.  Each developer is going to have their own system though, so feel free to close this as "too much" to redo at this stage.

I want you to really consider this though because the better organized your code is, the more likely other developers will submit patches, submit bug reports, and build on top of it.

**Classes:**

There's a lot of singleton classes in this plugin that encapsulate a lot of related code.  However, just because something is related, doesn't necessarily mean it needs to be within a class.

For example, `classes/class-admin.php` does a lot of "global" admin type things, such as set up admin pages, reorder menus, etc.  However, it also does things like register taxonomies, handle post relationships, and handle term metadata.  Many of these things should be separated into their own classes or functions outside of the main `LSX_TO_Admin` class.

In the long run, having something like the term metadata code separate from the main admin class is going to be much easier to manage.

**Includes vs. Admin:**

I'd recommend having an `includes` folder and an `admin` folder for storing files.  Anything in `admin` would only be loaded on the admin side.  Anything in `includes` would always be loaded.  The current `classes` folder would go into `includes`.

**File naming:**

My preference is naming files like this:

* `class-example.php` - Single class files.
* `functions-example.php` - File containing group of related functions.
* `template-example.php` - File containing group of related template tags.

You could do anything though.  Just be consistent.  Another option might be:

* `includes/classes/class-example.php`
* `includes/functions/example.php`
* `includes/template/example.php`

**Comment by krugazul** [comment]
Ive gone through the refactoring of the classes, the namespacing, the file structure change , the separation of the admin class and a few other updates.   We have merged it with the 1.1.0 branch.  Its all working now thanks @Desertsnowman
