### ISSUE TITLE
widget_title filter hook

### ISSUE THREAD

**Issue by justintadlock** [lightspeeddevelopment/tour-operator#56]
In your widgets, you're handling titles like this:

```
$title = apply_filters('widget_title', $instance['title']);
```

It's good that you're adding the core filter hook here.  However, you're missing the `$instance` and `$id_base` parameters, which other plugins may rely on.  See: https://developer.wordpress.org/reference/hooks/widget_title/

You'll want to code that like:

```
$title = apply_filters( 'widget_title', $instance['title'], $instance, $this->id_base );
```

**Comment by nandotess** [comment]
Closed automatically via commit. Function call updated.
