### ISSUE TITLE
Simplifying if/else statements

### ISSUE THREAD

**Issue by justintadlock** [lightspeeddevelopment/tour-operator#57]
A lot of people don't like ternary operators.  However, they have their place.  Looking through the TO Taxonomy widget in `includes/widgets/taxonomy-widget.php` (and the other widgets), you have lots of `if`/`else` statements such as:

```
if (isset($instance['title_link'])) {
	$title_link = $instance['title_link'];
} else {
	$title_link = false;
}
if (isset($instance['tagline'])) {
	$tagline = $instance['tagline'];
} else {
	$tagline = false;
}		
if (isset($instance['columns'])) {
	$columns = $instance['columns'];
} else {
	$columns = false;
}
```

That can become tough to read through.  I'd much rather code that like so:

```
$title_link = isset( $instance['title_link'] ) ? $instance['title_link'] : false;

$tagline = isset( $instance['tagline'] ) ? $instance['tagline'] : false;

$columns = isset( $instance['columns'] ) ? $instance['columns'] : false;
```

Ternary operators are a little harder to understand for people unfamiliar with them.  However, they can clean up code, and I find them really useful in situations where you have a huge list of `if`/`else` statements.

**Comment by justintadlock** [comment]
Another option is to set up an array of defaults, such as:

```
$defaults = array(
	'title_link' => false,
	'tagline'    => false,
	'columns'    => false
);
```

Then, parse that with `$instance` like:

```
$widget_args = wp_parse_args( $instance, $defaults );
```

That way, anything that's not set, will fall back to the default.

**Comment by krugazul** [comment]
The ternary operator has been outlawed by the new version of the WordPress Coding Standards, so this will not be fixed.
