### ISSUE TITLE
WP menu image resizing

### ISSUE THREAD

**Issue by Psycic101** [lightspeeddevelopment/tour-operator#62]
The following css found on line 1361 of admin.css and admin-rtl.css and line 1 of admin.min.css cause the admin images to resize incorrectly as shown in the images below:
`body.tour-operator_page_to-help img, body.tour-operator_page_to-addons img { width: 100%; }`
With CSS:
![css-enabled](https://user-images.githubusercontent.com/983667/27128391-93ce0bc8-50fe-11e7-97f1-498e02a552df.png)
Without CSS:
![css-disabled](https://user-images.githubusercontent.com/983667/27128402-9d75e65a-50fe-11e7-8e92-fd9d89ce708e.png)

**Comment by nandotess** [comment]
@Psycic101 thank you for your feedback. We will check your report ASAP and will let you know about the solution.

**Comment by Psycic101** [comment]
It looks like that code isn't really necessary, so could just be removed. But I haven't done any thorough testing.

**Comment by nandotess** [comment]
@Psycic101 new minor version (1.0.8) deployed with your reported issue fixed.
You can update the plugin directly in your plugins dashboard or you can download the latest version here:

- https://wordpress.org/plugins/tour-operator/

Hopefully, now it's everything working as expected. Thanks for using our Tour Operators plugin.
