### ISSUE TITLE
Add structured data support to the "Destinations" post type

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/tour-operator#71]
**Country** 

- [TO Demo](https://to-demo.lsdev.biz/destination/tanzania/)
- [Google Structure Tool](https://search.google.com/structured-data/testing-tool/u/0/?utm_campaign=devsite&utm_medium=jsonld&utm_source=review-snippet#url=https%3A%2F%2Fto-demo.lsdev.biz%2Fdestination%2Ftanzania%2F)

**State**

- [Demo](https://to-demo.lsdev.biz/destination/tanzania/central-serengeti/) 
- [Google Structured Tool](https://search.google.com/structured-data/testing-tool/u/0/?utm_campaign=devsite&utm_medium=jsonld&utm_source=review-snippet#url=https%3A%2F%2Fto-demo.lsdev.biz%2Fdestination%2Ftanzania%2Fcentral-serengeti%2F)

**Comment by krugazul** [comment]
**Accommodation**
- The Accommodation is added to the “containsPlace” parameter for a country and a region.

**Country (Destination)**
- This is a destination, without a parent, which outputs it children regions as “Places” in the “containsPlace” parameter.

**Region (Destination)**
- This is the child of a Country, and will show the “post parent” in the “containedIn” parameter.

**Specials**
- The accommodation price has been added as a “Standard” Offer.  
- “Standard” is a text value I chose to add to the Offer “Category” parameter.
- The Availability of this field is set to “OnlineOnly” as a Tour is not a physical product.
- Any special that is connected had been listed after that as “Special” Offers.
- The Availability of this offer is set as “LimitedAvailability” as a special expires.

**Reviews**
- The Reviews posts have been called as a “Review” under the “reviews” parameter of the destination.

**Blog posts**
- The Blog Posts have been called as an “Article” under the “subjectOf” parameter

**Tours (todo)**
 - How are we going to connect trips to the destinations, we need to find a parameter which allows this.

**Team (todo)**
- Looking at how to switch the “author” / “publisher” to this, or at least how to reference the team member.

**Comment by krugazul** [comment]
@ashleyshaw Ive gone through the Google Structured tool and fixed the errors, I had to remove reviews and specials as they are not allowed on a country / state yet.

**Country**
`containsPlace` - Connected Accommodation and Child Regions
`subjectOf`  - The connected posts
`geo` - the lat and long coordinates from the custom field

**State**
`containsPlace` - Connected Accommodation
`containedInPlace` - Parent Destination
`subjectOf`  - The connected posts
`geo` - the lat and long coordinates from the custom field

**Reviews** - We do not review a country, and currently the Review Schema doesnt allow reviews on a country.
**Team** - There isnt a field to connect this by
**Specials** - There isnt a field to connect this by
