### ISSUE TITLE
Add structured data support to the "Tours" post type

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/tour-operator#72]
- [Tour Demo Link](https://to-demo.lsdev.biz/tour/a-wild-tanzania-getaway/) 
- [Google Structured Testing Tool](https://search.google.com/structured-data/testing-tool/u/0/?utm_campaign=devsite&utm_medium=jsonld&utm_source=review-snippet#url=https%3A%2F%2Fto-demo.lsdev.biz%2Faccommodation%2Fgibbs-farm%2F)

There are 6 warning here, most of them are shared with the Accommodation post type as they both use `@type product`.

**Comment by krugazul** [comment]
- [Tour Demo Link](https://to-demo.lsdev.biz/tour/a-wild-tanzania-getaway/) 
- [Google Structured Testing Tool](https://search.google.com/structured-data/testing-tool/u/0/?utm_campaign=devsite&utm_medium=jsonld&utm_source=review-snippet#url=https%3A%2F%2Fto-demo.lsdev.biz%2Faccommodation%2Fgibbs-farm%2F)

There are 6 warning here, most of them are shared with the Accommodation post type as they both use `@type product`.

**Comment by krugazul** [comment]
**Accommodation + Destination**

- The main Trip schema, has the country destination (Country) as a node.
- Each subTrip has Places nodes as (itinerary),  specifically an Accommodation (Accommodation) and a Region (State).

**Specials**

- The tour price has been added as a “Standard” Offer.  
- “Standard” is a text value I chose to add to the Offer “Category” parameter.
- The Availability of this field is set to “OnlineOnly” as a Tour is not a physical product.
- Any special that is connected had been listed after that as “Special” Offers.
- The Availability of this offer is set as “LimitedAvailability” as a special expires.

**Reviews**

- The Reviews posts have been called as a “Review” under the “reviews” parameter of the “Trip”

**Blog posts**

- The Blog Posts have been called as an “Article” under the “subjectOf” parameter of the “Trip”.

**Team (todo)**

- This post type has not been connected yet,  a tour has either a “Person” or an “Organization”.  Currently we have the TO Demo Yoast settings to output an “Organization” which is set as the “Publisher” of the Tour (Trip)

**Comment by krugazul** [comment]
@ashleyshaw The tour is added as a Trip and a Product, we might not need the Product type,  I thought we needed it to add in a price,  but Trips have "Offers" which houses the pricing.  So we could remove `mpn`, `sku` and `identifier` by removing the additional `Product` type.

- `mpn` - post_id
- `sku` - wetu ID
- `identifier` - wetu ID
- `itinerary` - contains the connected destinations
- `subTrip` - contains the day to day itinerary along with the connected accommodation and the destination it is located in.
- `reviews` - all the connected reviews
- `offers` - The current tour price, and the connected specials
- `subjectOf` - the connected articles
- `provider` - The Yoast Organization Settings
