### ISSUE TITLE
Add structured data support to the "Accommodation" post type

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/tour-operator#73]
- [Accommodation Demo link](https://to-demo.lsdev.biz/accommodation/gibbs-farm/)
- [Google Structured Tool ](https://search.google.com/structured-data/testing-tool/u/0/?utm_campaign=devsite&utm_medium=jsonld&utm_source=review-snippet#url=https%3A%2F%2Fto-demo.lsdev.biz%2Faccommodation%2Fgibbs-farm%2F)

There are 7 "recommended" warnings that need to be looked at.

**Comment by krugazul** [comment]
Demo link - https://to-demo.lsdev.biz/accommodation/gibbs-farm/
[Google Structured Tool ](https://search.google.com/structured-data/testing-tool/u/0/?utm_campaign=devsite&utm_medium=jsonld&utm_source=review-snippet#url=https%3A%2F%2Fto-demo.lsdev.biz%2Faccommodation%2Fgibbs-farm%2F)

There are 7 "recommended" warnings that need to be looked at.

**Comment by krugazul** [comment]
Destinations
- The destinations are added via the “containedIn” parameter as (Country + State)
Specials
 - The accommodation price has been added as a “Standard” Offer., “Standard” is a text value I chose to add to the Offer “Category” parameter.
 - The Availability of this field is set to “OnlineOnly” as a Tour is not a physical product.
 - Any special that is connected had been listed after that as “Special” Offers, The Availability of this offer is set as “LimitedAvailability” as a special expires.
Reviews
- The Reviews posts have been called as a “Review” under the “reviews” parameter
Blog posts
- The Blog Posts have been called as an “Article” under the “subjectOf” parameter


Tours (todo)
 - I am looking at the Trips to where / if we can connect these.
Team (todo)
 - How do we connect a team / person to the accommodation?  As the publisher, or maybe there is a manager tag we could use.

**Comment by krugazul** [comment]
@ashleyshaw ive run through the Accommodation and these are the fields connected.   I have not listed the description and name, as those are the post title and post content.

- `sku` - wetu ID
- `reviews` - all the connected reviews
- `offers` - The current accommodation price, and the connected specials
- `subjectOf` - the connected articles
- `identifier` - wetu ID
- `itinerary` - contains the connected destinations
- `subTrip` - contains the day to day itinerary along with the connected accommodation and the destination it is located in.
- `containedIn` - The connected destinations
- `provider` - The Yoast Organization Settings
- `subjectOf` - The connected posts
- `numberOfRooms` - custom field
- `geo` - the lat and long coordinates from the custom field
- 'amenityFeature' - Facilities taxonomy


**Tours** - We dont have a relevant field to describe this accommodation is part of a tour.
**Team** - There isnt a field to say this accommodation has a contact person (team member).
