### ISSUE TITLE
Remove the flag-icons vendor CSS and Images

### ISSUE THREAD

**Issue by krugazul** [lightspeeddevelopment/tour-operator#74]
We can remove the flag-icon vendor CSS and Images,  we dont not use it anywhere in the TO Plugin.   The only place we output flag icons is in the LSX Currencies plugin, which already includes its own flag icons.

- [x] Remove the [style.scss](https://github.com/lightspeeddevelopment/tour-operator/blob/master/assets/css/scss/style.scss#L8) declaration
- [x] Remove the [admin.scss](https://github.com/lightspeeddevelopment/tour-operator/blob/master/assets/css/scss/admin.scss#L5) declaration
- [x] Remove the [flag-icon-css](https://github.com/lightspeeddevelopment/tour-operator/tree/master/assets/css/vendor) folder
- [x] Remove it from the [devDependancies](https://github.com/lightspeeddevelopment/tour-operator/blob/master/package.json#L29)
- [x] Remove the [Gulp Tasks](https://github.com/lightspeeddevelopment/tour-operator/blob/master/gulpfile.js#L214)
- [x] Test that nothing breaks in the frontend 
- [x] Test that nothing breaks in the backend

**Comment by viscosho** [comment]
This process was done on this commit: https://github.com/lightspeeddevelopment/tour-operator/commit/0b970792250d7a967472949b7d6db4e9dec69140
Tested on local and demo, working ok on front and on the admin area.
Closing.

**Comment by krugazul** [comment]
@viscosho I have checked this as well, no errors.
