### ISSUE TITLE
Add the enhanced sitemap.php page template to TO core

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/tour-operator#75]
Create a page template that has a Sitemap that lists all the Post Types, Taxonomies and Pages on the site:

- [x] The page should have a 'Sitemap' title
- [x] Each one should show in a section
- [x] Each section should have a title
- [x] Each section should have a list with all the items related to that section, this should be dynamic content.
- [x] For content like Destinations, the lists should have hierarchy, showing the parten continent as a list item, the countries of that Continent as sub items and the regions as sub items too. And each country or continent should be a separate list. Instead of having a random list of all destinations, all the regions are grouped under their destination. and all subregions are grouped under the regions.

**Comment by viscosho** [comment]
This has been created on this branch: https://github.com/lightspeeddevelopment/tour-operator/pull/96

**Comment by krugazul** [comment]
This was fixed and merged in on pull request #96
