### ISSUE TITLE
Single Post Type navigation to move below banner when LSX Banners is not active.

### ISSUE THREAD

**Issue by krugazul** [lightspeeddevelopment/tour-operator#76]
@viscosho  If you look at a single accommodation / tour / destination on the TO Template site, you will see the Page Navigation sits behind the breadcrumbs.  LSX Banners is not active on this site, so you need to please make sure that it sits below the page banner.

- TO Template Site - [Example of Problem](https://to-template.feedmybeta.com/tour/a-taste-of-tanzania/)
- TO Demo Site - [Example](https://to-demo.lsdev.biz/tour/a-wild-tanzania-getaway/) of what is should look like

**Comment by viscosho** [comment]
@krugazul  this was fixed here: https://github.com/lightspeeddevelopment/tour-operator/commit/081a060e6e2aedea3240ea08fce3e56939b36921
Please review
