### ISSUE TITLE
The Google Maps need some spacing between them when LSX Banners is not active.

### ISSUE THREAD

**Issue by krugazul** [lightspeeddevelopment/tour-operator#77]
@viscosho if you look at all the pages that a map outputs, you will see it needs some space between it and the section above.  This happens when LSX banners is not active.

- https://to-template.feedmybeta.com/continent/africa/
- https://to-template.feedmybeta.com/destination/tanzania/
- https://to-template.feedmybeta.com/destination/tanzania/karatu/
- https://to-template.feedmybeta.com/tour/a-taste-of-tanzania/
- https://to-template.feedmybeta.com/accommodation/one-nature-nyaruswiga/

**Comment by viscosho** [comment]
This was fixed on this PR https://github.com/lightspeeddevelopment/tour-operator/pull/94
