### ISSUE TITLE
Grouping of Post Type and Taxonomy Widget Options

### ISSUE THREAD

**Issue by krugazul** [lightspeeddevelopment/tour-operator#78]
We need to reorder the current widget options into groups, this will help with understanding what and how to configure the widget.

No Heading
 - Class: (input)

Header
 - Title: (input)
 - Title Link: (input)

Query
 - Post Type: (dropdown)
 - Order By: (dropdown)
 - Order: (dropdown)
 - Maximum amount: (input)
 - Specify by ID: (input)
 - Parents Only (checkbox)
 - Featured Items (checkbox)

Display
 - Columns: (dropdown)
 - Disable Featured Image (checkbox)
 - Disable Excerpt and Tagline (checkbox)
 - Disable View More Button (checkbox)

Carousel
 - Enable Carousel (checkbox)
 - Slide Interval: (input)

Footer
 - Display Button (checkbox)
 - Button Text: (input)

**Comment by ashleyshaw** [comment]
@krugazul do we need any language or description improvements for any of the interfaces elements? Please work with @garthglaum to improve these and if need be you can request a design from @deonschreiber
