### ISSUE TITLE
Move the description text on main Tour & Accommodation archive above the filters

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/tour-operator#80]
![Tours Archive - Africa Travel Centre](https://user-images.githubusercontent.com/1805352/66598403-43b97380-eba1-11e9-9d44-19133b7ae2c1.png)

**Comment by deonschreiber** [comment]
![Screenshot 2019-10-25 at 14 20 34](https://user-images.githubusercontent.com/31090573/67570886-c4947580-f732-11e9-9366-fcdb9195238d.png)
@viscosho Please see attached screen shot. I've updated the design to reflect this

**Comment by viscosho** [comment]
@deonschreiber  this has been fixed in this branch: https://github.com/lightspeeddevelopment/tour-operator/tree/fix-80

Here is the pull request: https://github.com/lightspeeddevelopment/tour-operator/pull/88
