### ISSUE TITLE
Add in "sticky posts" functionality for destinations.

### ISSUE THREAD

**Issue by krugazul** [lightspeeddevelopment/tour-operator#83]
### Development - Backend - Edit Post
- [x] Add in a checkbox to destinations labelled "Stick to the Archive Page", this will sit below the "featured" checkbox.

### Development - Backend - Theme Options
- [x] Add in a drop down to allow the option to enable (Only sticky destinations, sticky and non sticky destinations.)

### Development - Frontend - Archives
- [x] Edit the pre_get_posts function, check if the sticky posts have bee activated.
- [x] If so the edit the WP_Query statement to include the sticky posts first

**Comment by krugazul** [comment]
@ashleyshaw This work has been completed.   There was one slight change to the custom field on the single destinations.   Instead of a checkbox, it is a text input like the "menu_order" field.  So you can enter a numerical value, and arrange the "sticky" destinations.

**Comment by krugazul** [comment]
Test Case - The following instructions show you how to activate "sticky" destinations for the post type archives and country pages.  
- Stick Destinations to the front of the loop on the archive page or country
- Stick Destinations to the back of the loop on the archive page or country
- Display only the "sticky" destinations on the archive or country page.

1a: **Tour Operator Settings** - [Destination Archives](https://to-demo.lsdev.biz/wp-admin/admin.php?page=lsx-to-settings)
Navigate to the Destinations -> Archives tab of the Tour Operator Settings and you will now see a `Sticky Destinations` drop down, select one of the options and save your settings.

![Theme-Options-Destinations](https://user-images.githubusercontent.com/1805603/67457065-ec9caf80-f632-11e9-8bee-b7599a325d4e.png)

1a: **Tour Operator Settings** - [Destination Countries](https://to-demo.lsdev.biz/wp-admin/admin.php?page=lsx-to-settings)
Click through to the "Single" tab and you will see a `Stick Countries` dropdown. This works exactly the same as the archives, but only on the country page.

![Settings-Single-Destinations](https://user-images.githubusercontent.com/1805603/67457268-83696c00-f633-11e9-8dfa-869c93a36680.png)

2: **Edit Destination**
When editing a destination you will now see a `Sticky Order` field, by default it will be set to `0`.  Here you can enter a numerical value to order your sticky posts. They will be displayed on the archive in ascending order.
- [South Africa](https://to-demo.lsdev.biz/wp-admin/post.php?post=173&action=edit&classic-editor)
- [Botswana](https://to-demo.lsdev.biz/wp-admin/post.php?post=124&action=edit&classic-editor)
 - [Namibia](https://to-demo.lsdev.biz/wp-admin/post.php?post=24605&action=edit&classic-editor)

![edit-destination](https://user-images.githubusercontent.com/1805603/67457622-78fba200-f634-11e9-87a8-57ceccc2fe2d.png)

3: **Destination Archive**
Depending on the option chose, your sticky posts should display in front, behind or only sticky destinations.  NB the post type archive only pulls through countries and not regions.

4: **Country** 
Depending on the option chose, your sticky posts should display in front, behind or only sticky destinations.

**Comment by viscosho** [comment]
Closing this one, I have review this, all ok.
