### ISSUE TITLE
The button styles have broken

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/tour-operator#89]
[https://www.bugherd.com/projects/96228/tasks/645](https://www.bugherd.com/projects/96228/tasks/645)

**Comment by ashleyshaw** [comment]
Fixed on core TO

**Comment by viscosho** [comment]
This was fixed on this PR https://github.com/lightspeeddevelopment/tour-operator/pull/94

**Comment by ashleyshaw** [comment]
checked
