### ISSUE TITLE
Single destination header styling (no lsx banner)

### ISSUE THREAD

**Issue by krugazul** [lightspeeddevelopment/tour-operator#9]
If you disable the LSX Banner plugin, then the navigation and the breadcrumbs conflict.  Could you please fix with CSS.

Also, if you set the layout to 2 columns, then the sidebar floats a bit upwards. which sits over the navgation and the breadcrumb.

![screen shot 2016-10-20 at 9 06 15 pm](https://cloud.githubusercontent.com/assets/1805603/19574148/517e1cae-9709-11e6-9aac-127a621bffa6.png)

**Comment by nandotess** [comment]
@krugazul initial issue reported was fixed. The second issue (related with 2 columns layout) I need more details how can I replicate. See the task #12, thanks.
