### ISSUE TITLE
This needs to be centered

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/tour-operator#90]
[https://www.bugherd.com/projects/96228/tasks/647](https://www.bugherd.com/projects/96228/tasks/647)

**Comment by ashleyshaw** [comment]
This was fixed here: https://github.com/lightspeeddevelopment/lsx/pull/292

**Comment by viscosho** [comment]
This one is an LSX core issue, closing, it if addressed on LSX
