### ISSUE TITLE
Fix this issue

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/tour-operator#91]
**Describe Issue**
When there is just 1 item, the to widgets look way too big.

**To Reproduce**
- Go to any single TO page that has a widget section with just 1 item.

**Screenshot**
![screenshot](https://user-images.githubusercontent.com/3129483/70755246-11023780-1d18-11ea-8467-f313df371eb1.jpg)

**Reference**
[https://www.bugherd.com/projects/96228/tasks/646](https://www.bugherd.com/projects/96228/tasks/646)

**Comment by ashleyshaw** [comment]
@[Deon Schreiber](184670)  please take a look at my solution for these items that only have 1 item

**Comment by viscosho** [comment]
This was fixed in this PR https://github.com/lightspeeddevelopment/tour-operator/pull/94

**Comment by ashleyshaw** [comment]
happy with that
