### ISSUE TITLE
The layout on this page does not look right

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/tour-operator#92]
**Describe the issue**
The layout on these archive pages does not look right, when the map is below it needs spacing.

**To Reproduce**
- Go to any TO archive page that has a map enabled.

**Screenshot**
![screenshot](https://user-images.githubusercontent.com/3129483/70754675-92f16100-1d16-11ea-97c3-7102c4ad63a9.jpg)

**Reference**
[https://www.bugherd.com/projects/96228/tasks/643](https://www.bugherd.com/projects/96228/tasks/643)

**Comment by ashleyshaw** [comment]
Fixed on core TO, you can see it here: http://to-demo.local/destinations/

**Comment by viscosho** [comment]
Fixes for this can be found in this PR https://github.com/lightspeeddevelopment/tour-operator/pull/94

**Comment by ashleyshaw** [comment]
unable to access that link on your local, moving this back to doing. This fix should still be displaying on this site though right?

**Comment by ashleyshaw** [comment]
@[Deon Schreiber](184670) please review https://to-template.feedmybeta.com/destinations/ I synced the branch there for testing
